---
apiVersion: "cert-manager.io/v1alpha2"
kind: "ClusterIssuer"
metadata:
  name: "letsencrypt-production"
  namespace: django-test
spec:
  acme:
    email: youemail@insert.here
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
...
