apiVersion: v1
kind: Service
metadata:
  labels:
    app: django-app
  name: django-app-service
  namespace: django-test
  resourceVersion: "10470"
  selfLink: /api/v1/namespaces/django-test/services/django-app-service
  uid: 72ca94c7-2bcf-11ea-8504-42010a80024e
spec:
  clusterIP: 10.0.12.99
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32109
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: django-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.225.76.83
...
